puts "🌱 Seeding spices..."

pennsylvania = Location.create(state: "Pennsylvania") 
chicago = Location.create(state: "Chicago") 
new_york = Location.create(state: "New York") 
colorado = Location.create(state: "Colorado") 
wyoming = Location.create(state: "Wyoming") 
california = Location.create(state: "California") 
arizona = Location.create(state: "Arizona") 
oregon = Location.create(state: "Oregon") 

pennsylvania.attractions.create(name: "Mutter Museum")
chicago.attractions.create(name: "Grant Park and Buckingham Fountain")
chicago.attractions.create(name: "Adler Planetarium")
chicago.attractions.create(name: "Shedd Aquarium")
chicago.attractions.create(name: "Chicago Cultural Center")
new_york.attractions.create(name: "Lake George")
new_york.attractions.create(name: "Angry Orchard Vineyard")
colorado.attractions.create(name: "Rocky Mountain National Park")
colorado.attractions.create(name: "Mesa Verde National Park")
wyoming.attractions.create(name: "Grand Prismatic Spring")
california.attractions.create(name: "Yosemite National Park")
california.attractions.create(name: "Vichy Springs")
arizona.attractions.create(name: "Grand Canyon National Park")
oregon.attractions.create(name: "Portland Japanese Garden")
oregon.attractions.create(name: "Pittock Mansion")
oregon.attractions.create(name: "Crystal Springs Rhododendron Garden")

chicago.restaurants.create(name: "Superdawg Drive-In")
chicago.restaurants.create(name:  "Lou Malnati's")
new_york.restaurants.create(name: "SakeMai")
colorado.restaurants.create(name: "Far View Lounge")
arizona.restaurants.create(name: "El Tovar Dining Room")
oregon.restaurants.create(name: "Bhuna")
oregon.restaurants.create(name:  "Casa Zoraya")

puts "✅ Done seeding!"
