puts "🌱 Seeding spices..."

pennsylvania = Location.create(state: "Pennsylvania") 
chicago = Location.create(state: "Chicago") 
new_york = Location.create(state: "New York") 
colorado = Location.create(state: "Colorado") 
wyoming = Location.create(state: "Wyoming") 
california = Location.create(state: "California") 
arizona = Location.create(state: "Arizona") 
oregon = Location.create(state: "Oregon") 

pennsylvania.attractions.create(attractionName: "Mutter Museum")
chicago.attractions.create(attractionName: "Grant Park and Buckingham Fountain")
chicago.attractions.create(attractionName: "Adler Planetarium")
chicago.attractions.create(attractionName: "Shedd Aquarium")
chicago.attractions.create(attractionName: "Chicago Cultural Center")
new_york.attractions.create(attractionName: "Lake George")
new_york.attractions.create(attractionName: "Angry Orchard Vineyard")
colorado.attractions.create(attractionName: "Rocky Mountain National Park")
colorado.attractions.create(attractionName: "Mesa Verde National Park")
wyoming.attractions.create(attractionName: "Grand Prismatic Spring")
california.attractions.create(attractionName: "Yosemite National Park")
california.attractions.create(attractionName: "Vichy Springs")
arizona.attractions.create(attractionName: "Grand Canyon National Park")
oregon.attractions.create(attractionName: "Portland Japanese Garden")
oregon.attractions.create(attractionName: "Pittock Mansion")
oregon.attractions.create(attractionName: "Crystal Springs Rhododendron Garden")

chicago.restaurants.create(restaurantName: "Superdawg Drive-In")
chicago.restaurants.create(restaurantName:  "Lou Malnati's")
new_york.restaurants.create(restaurantName: "SakeMai")
colorado.restaurants.create(restaurantName: "Far View Lounge")
arizona.restaurants.create(restaurantName: "El Tovar Dining Room")
oregon.restaurants.create(restaurantName: "Bhuna")
oregon.restaurants.create(restaurantName:  "Casa Zoraya")

puts "✅ Done seeding!"
